In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [2]:
wine_red_df = pd.read_csv("data/winequality-red.csv", sep = ";")
wine_white_df = pd.read_csv("data/winequality-white.csv", sep = ";")

In [3]:
wine_red_df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [72]:
data = wine_red_df.values

In [79]:
x_red = data[:,0:-1]
y_red = data[:,-1]

In [80]:
x_red_train, x_red_test, y_red_train, y_red_test = train_test_split(x_red,y_red,test_size = 0.3)

In [81]:
#scale = StandardScaler().fit(x_red_train)
#scale.transform(x_red_train)
#scale.transform(x_red_test)

In [82]:
x_red_train,x_red_test

(array([[ 7.9  ,  0.34 ,  0.42 , ...,  3.35 ,  0.6  , 11.4  ],
        [10.9  ,  0.37 ,  0.58 , ...,  3.22 ,  0.78 , 10.1  ],
        [11.5  ,  0.59 ,  0.59 , ...,  3.18 ,  0.65 , 11.   ],
        ...,
        [ 7.7  ,  0.51 ,  0.28 , ...,  3.42 ,  0.74 ,  9.2  ],
        [ 7.   ,  0.805,  0.   , ...,  3.48 ,  0.56 ,  9.6  ],
        [ 9.2  ,  0.56 ,  0.18 , ...,  3.15 ,  0.49 ,  9.9  ]]),
 array([[11.  ,  0.2 ,  0.48, ...,  3.3 ,  0.71, 10.5 ],
        [ 6.2 ,  0.64,  0.09, ...,  3.57,  0.63, 12.  ],
        [11.3 ,  0.62,  0.67, ...,  3.22,  0.69, 13.4 ],
        ...,
        [ 6.1 ,  0.6 ,  0.08, ...,  3.38,  0.54, 11.  ],
        [ 8.2 ,  0.5 ,  0.35, ...,  3.23,  0.62,  9.4 ],
        [10.  ,  0.69,  0.11, ...,  2.88,  0.47,  9.7 ]]))

In [83]:
scale = MinMaxScaler(feature_range = (0,10),copy = True)
x_red_train = scale.fit_transform(x_red_train)
x_red_test = scale.transform(x_red_test)
x_red_train, x_red_test

(array([[2.92035398, 1.81818182, 4.2       , ..., 4.80314961, 1.61676647,
         4.61538462],
        [5.57522124, 2.0661157 , 5.8       , ..., 3.77952756, 2.69461078,
         2.61538462],
        [6.10619469, 3.88429752, 5.9       , ..., 3.46456693, 1.91616766,
         4.        ],
        ...,
        [2.74336283, 3.2231405 , 2.8       , ..., 5.35433071, 2.45508982,
         1.23076923],
        [2.12389381, 5.66115702, 0.        , ..., 5.82677165, 1.37724551,
         1.84615385],
        [4.07079646, 3.63636364, 1.8       , ..., 3.22834646, 0.95808383,
         2.30769231]]),
 array([[5.66371681, 0.66115702, 4.8       , ..., 4.40944882, 2.2754491 ,
         3.23076923],
        [1.4159292 , 4.29752066, 0.9       , ..., 6.53543307, 1.79640719,
         5.53846154],
        [5.92920354, 4.1322314 , 6.7       , ..., 3.77952756, 2.15568862,
         7.69230769],
        ...,
        [1.32743363, 3.96694215, 0.8       , ..., 5.03937008, 1.25748503,
         4.        ],
        [3.1

In [84]:
df = pd.DataFrame(x_red_train)
df.columns = wine_red_df.columns[0:-1]
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1119.000000       1119.000000  1119.000000     1119.000000   
mean        3.302649          3.399323     2.714567        1.145111   
std         1.500615          1.466078     1.949738        0.969835   
min         0.000000          0.000000     0.000000        0.000000   
25%         2.300885          2.314050     1.000000        0.689655   
50%         2.920354          3.305785     2.500000        0.896552   
75%         4.070796          4.297521     4.200000        1.172414   
max        10.000000         10.000000    10.000000       10.000000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1119.000000          1119.000000           1119.000000  1119.000000   
mean      1.290891             2.070322              1.435501     4.915739   
std       0.837949             1.469588              1.180176     1.394083   
min       0.000000             0.000000              0.000000     0.000000   
25%       0.984975             0.845070              0.565371     4.096916   
50%       1.135225             1.830986              1.095406     4.941263   
75%       1.335559             2.816901              1.996466     5.723201   
max      10.000000            10.000000             10.000000    10.000000   

                pH    sulphates      alcohol  
count  1119.000000  1119.000000  1119.000000  
mean      4.472216     1.958603     3.112784  
std       1.210498     1.023380     1.671303  
min       0.000000     0.000000     0.000000  
25%       3.700787     1.317365     1.692308  
50%       4.409449     1.736527     2.615385  
75%       5.196850     2.395210     4.153846  
max      10.000000    10.000000    10.000000

In [70]:
from sklearn.neighbors import KNeighborsClassifier


In [85]:
max_score = 0
opt_k = 0
for k in range(3,100):
    alg = KNeighborsClassifier(n_neighbors = k)
    alg.fit(x_red_train,y_red_train)
    score = alg.score(x_red_test,y_red_test)
    if(score>max_score):
        max_score = score
        opt_k = k
max_score, opt_k

(0.6291666666666667, 46)

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
max_score = 0
opt_k = 0
for k in range(3,100):
    alg = RandomForestClassifier(n_estimators = k)
    alg.fit(x_red_train,y_red_train)
    score = alg.score(x_red_test,y_red_test)
    if(score>max_score):
        max_score = score
        opt_k = k
max_score, opt_k

(0.70625, 86)